### ISSUE TITLE
Limit area in activity for swipe back

### ISSUE THREAD

**Issue by Mfrenchy77** [sockeqwe/SwipeBack#12]
Love your library. Is there a way to limit the swipe back area on the activity? I am running into an issue when trying to scroll around on a webView, if I scroll right the swipe back  gets activated. Would like to limit it to a smaller area if you know what I mean.

Thanks

**Comment by sockeqwe** [comment]
Hi, this can be done globally in your activities theme in xml:
```
<sbBezelSize>10dp</sbBezelSize>
```

**Comment by Mfrenchy77** [comment]
Not sure how to implement this. Is it wrapped in an <item> tag?

**Comment by Ftoma123** [comment]
Hi
Your code is a collection of swipe back method, I couldn't extract the simple method for doing it.
So could you please rewrite the code for simple swipe back without unrelated classes?
Thank you

**Comment by Gryzor** [comment]
^ lol
