### ISSUE TITLE
Does this lib have onSwipeBackListener?

### ISSUE THREAD

**Issue by ngocht143** [sockeqwe/SwipeBack#13]
Hi @sockeqwe,
Can i use this lib for fragment? I want to override the listener when user swipe back (not finish my activity). Is your lib support this issue? :)

**Comment by sockeqwe** [comment]
Hi,
I have never used it with Fragments, but it should be possible.

What you are looking for can be achieved with a `SwipeBackTransformer`, that is the "listner" you are looking for:
```java
SwipeBack.attach(this, Position.LEFT)
        .setSwipeBackTransformer(new YourFragmentSwipeBackTransformer())
         ...
```
https://github.com/sockeqwe/SwipeBack/blob/master/library/src/com/hannesdorfmann/swipeback/transformer/DefaultSwipeBackTransformer.java
