### ISSUE TITLE
How to set swipeback container transparent

### ISSUE THREAD

**Issue by kangnixi** [sockeqwe/SwipeBack#16]
I try to use 

`.setSwipeBackContainerBackgroundColor(android.R.color.transparent)`

it doesn't work

**Comment by sockeqwe** [comment]
Never done that before, but  I think you are on the right track with `.setSwipeBackContainerBackgroundColor(android.R.color.transparent)`. Additionally you have to set the  (or remove) activities background as described here: http://nullpointerbay.com/2015/08/13/android-appcompat-design-lib-activity-transparency.html

**Comment by kangnixi** [comment]
Thanks for your replied
I resolve it.
except your said

it need to set MainActivity style:
` <item name="android:windowIsTranslucent">false</item>
  <item name="android:windowBackground">@color/windowBackgroundGray</item>
  <item name="android:colorBackgroundCacheHint">@null</item>`

And set other swipe back activity style: 
` <item name="android:windowIsTranslucent">true</item>
  <item name="android:windowBackground">@android:color/transparent</item>`

I have another question, how to set mSwipeBackViewSize by xml

Now I set it by code:
`SwipeBack.setSize(100)`
