### ISSUE TITLE
I want to remove SwipeBackView?

### ISSUE THREAD

**Issue by khacdat1994** [sockeqwe/SwipeBack#23]
Hello,
I want to remove SwipeBackView? When you swipe left to right to back first activity without swipebackview. hELP ME PLEASE

**Comment by khacdat1994** [comment]
![37940895_1886610908075133_7829634580704395264_n](https://user-images.githubusercontent.com/12053977/43368233-65a1a8f8-9384-11e8-8eaf-195b3fbc4e09.jpg)
That's it! I want to remove it. thank

**Comment by sockeqwe** [comment]
Then don't use this library (SwipeBackActivity) at all?!?!?

**Comment by risefire** [comment]
you can set the size as 1 and to swipe from the edge set the touch mode as 1
  SwipeBack.attach(this, Position.LEFT)
                .setContentView(R.layout.homepage)
                .setSwipeBackView(R.layout.swipeback_default)
                .setSize(1)
                .setTouchMode(1)
                .setSwipeBackTransformer(new SlideSwipeBackTransformer() {
                    @Override
                    public void onSwipeBackCompleted(SwipeBack swipeBack, Activity activity) {
                       onBackPressed();
                    }
                });
