### ISSUE TITLE
How change text caption?

### ISSUE THREAD

**Issue by Radzhab** [sockeqwe/SwipeBack#9]
I cannot find method to change text when i drag fragment

ex
```java
 SwipeBack.attach(this, Position.LEFT)
                .setContentView(R.layout.fragment_blank)
                .setSwipeBackView(R.layout.swipeback_default)
                .setText("BACK TO MAIN");
```

**Comment by sockeqwe** [comment]
The easiest way is to define a custom layout
`.setSwipeBackView(R.layout.my_swipeback_layout)`

you could copy and paste the `R.layout.swipeback_default` and customize it
